apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vx6w7cmmm-nodejs 
  janus-idp.io/tekton: vx6w7cmmm-nodejs
  backstage.io/kubernetes-id: vx6w7cmmm-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vx6w7cmmm-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml