apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vx6w7cmmm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vx6w7cmmm-nodejs 
  name: vx6w7cmmm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vx6w7cmmm-nodejs 
